export const SET_POKEMON = 'SET_POKEMON';
export const SET_ERROR = 'SET_ERROR';
export const CLEAN_ERROR = 'CLEAN_ERROR';
export const FETCH_POKEMONS_WITH_DETAILS = 'FETCH_POKEMONS_WITH_DETAILS';
export const TOGGLE_LOADER = 'TOGGLE_LOADER';